// front/components/LoginForm.tsx
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import useAuthStore from "@/stores/auth";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { loginSchema, type LoginSchema } from "@/schemas/auth.schema";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function LoginForm() {
  const router = useRouter();
  const { login } = useAuthStore();
  const [isLoading, setIsLoading] = useState(false);

  const form = useForm<LoginSchema>({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      email: "",
      password: "",
    },
  });

  async function onSubmit(data: LoginSchema) {
    setIsLoading(true);
    const response = await login(data);
    if (response.status === "success") {
      router.push("/");
      toast.success("Connexion réussie");
    } else {
      toast.error(response.message);
    }
    setIsLoading(false);
  }

  return (
    <Card className="max-w-md mx-auto">
      <CardHeader>
        <CardTitle>Connexion</CardTitle>
        <CardDescription>
          Vous n'avez pas de compte ?{" "}
          <Link href="/signup" className="text-blue-500">
            Inscrivez-vous
          </Link>
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="w-full space-y-6"
          >
            <FormField
              control={form.control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Email</FormLabel>
                  <FormControl>
                    <Input
                      type="email"
                      placeholder="jean.dupont@example.com"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="password"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Mot de passe</FormLabel>
                  <FormControl>
                    <Input type="password" placeholder="••••••••" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <Button type="submit" disabled={isLoading}>
              {isLoading ? "Connexion..." : "Se connecter"}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}

// frontend/components/LoginForm.vue
<script setup lang="ts">
import type { FormSubmitEvent } from "#ui/types";
import { loginSchema, type LoginSchema } from "~/schemas/auth.schema";
import { useAuthStore } from "~/store/auth";

const toast = useToast();
const authStore = useAuthStore();
const isOpen = ref(false);
const isLoading = ref(false);
const errorMessage = ref("");
const state = reactive({
  email: "",
  password: "",
});

async function onSubmit(event: FormSubmitEvent<LoginSchema>) {
  isLoading.value = true;

  try {
    await authStore.authenticate(event.data);
    toast.add({ title: "Connexion réussie" });
    navigateTo("/");
    isOpen.value = false;
  } catch (error) {
    console.log(error);
  }

  isLoading.value = false;
}
</script>

<template>
  <div>
    <UCard class="max-w-md mx-auto">
      <div class="mb-8 text-center">
        <h2 class="text-3xl font-bold mb-2">Connexion</h2>
        <p class="text-sm text-gray-500">
          Vous n'avez pas de compte ?
          <NuxtLink to="/signup" class="text-primary-500">
            Inscrivez-vous
          </NuxtLink>
        </p>
      </div>
      <UForm
        :schema="loginSchema"
        :state="state"
        class="space-y-4"
        @submit="onSubmit"
      >
        <UFormField class="w-full" label="Email" name="email" required>
          <UInput v-model="state.email" class="w-full" />
        </UFormField>

        <UFormField
          class="w-full"
          label="Mot de passe"
          name="password"
          required
        >
          <UInput v-model="state.password" type="password" class="w-full" />
        </UFormField>

        <p v-if="errorMessage" class="text-red-500">{{ errorMessage }}</p>

        <UButton class="!mt-6" type="submit" :loading="isLoading" block>
          Se connecter
        </UButton>
      </UForm>
    </UCard>
  </div>
</template>
