// frontend/components/SignupForm.vue
<script setup lang="ts">
import type { FormSubmitEvent } from "#ui/types";
import { signupSchema, type SignupSchema } from "~/schemas/auth.schema";

const endpoint = useRuntimeConfig().public.apiBase;

const initialState: {
  firstname: string;
  lastname: string;
  email: string;
  password: string;
  licenseNumber: string | null;
} = {
  firstname: "",
  lastname: "",
  email: "",
  password: "",
  licenseNumber: null,
};

const toast = useToast();
const isOpen = ref(false);
const state = reactive(initialState);
const errorMessage = ref("");
const isLoading = ref(false);
const showPassword = ref(false);
const isLicense = ref(false);

async function onSubmit(event: FormSubmitEvent<SignupSchema>) {
  isLoading.value = true;

  const { status, error } = await useFetch(`${endpoint}/auth/signup`, {
    method: "POST",
    body: {
      ...event.data,
    },
    credentials: "include",
  });

  isLoading.value = false;

  if (status.value === "success") {
    resetForm();
    toast.add({ title: "Inscription réussie" });
  } else {
    errorMessage.value = error.value?.data.message;
  }
}

const resetForm = () => {
  isOpen.value = false;
  state.lastname = "";
  state.firstname = "";
  state.email = "";
  state.password = "";
  state.licenseNumber = null;
};
</script>

<template>
  <div>
    <UCard class="max-w-md mx-auto">
      <div class="mb-8 text-center">
        <h2 class="text-3xl font-bold mb-2">Inscription</h2>
        <p class="text-sm text-gray-500">
          Vous avez déjà un compte ?
          <NuxtLink to="/login" class="text-primary-500">
            Connectez-vous
          </NuxtLink>
        </p>
      </div>
      <UForm
        :schema="signupSchema"
        :state="state"
        class="space-y-4"
        @submit="onSubmit"
      >
        <div class="flex gap-4">
          <UFormField class="w-full" label="Prénom" name="firstname" required>
            <UInput v-model="state.firstname" class="w-full" />
          </UFormField>

          <UFormField class="w-full" label="Nom" name="lastname" required>
            <UInput v-model="state.lastname" class="w-full" />
          </UFormField>
        </div>

        <UFormField class="w-full" label="Email" name="email" required>
          <UInput v-model="state.email" class="w-full" />
        </UFormField>

        <UFormField
          class="w-full"
          label="Mot de passe"
          name="password"
          required
        >
          <UInput
            v-model="state.password"
            class="w-full"
            :type="showPassword ? 'text' : 'password'"
            :ui="{ trailing: 'pe-1' }"
          >
            <template #trailing>
              <UButton
                color="neutral"
                variant="link"
                size="sm"
                :icon="showPassword ? 'i-lucide-eye-off' : 'i-lucide-eye'"
                :aria-label="showPassword ? 'Hide password' : 'Show password'"
                :aria-pressed="showPassword"
                aria-controls="password"
                @click="showPassword = !showPassword"
              />
            </template>
          </UInput>
        </UFormField>

        <UCheckbox
          v-model="isLicense"
          label="J'ai ma licence de Padel 2025"
          class="mb-4"
        />

        <UFormField
          class="w-full"
          label="Numéro de licence"
          name="licenseNumber"
          v-if="isLicense"
        >
          <UInput v-model="state.licenseNumber" class="w-full" />
        </UFormField>

        <p v-if="errorMessage" class="text-red-500">{{ errorMessage }}</p>

        <UButton class="!mt-4" type="submit" :loading="isLoading" block>
          S'inscrire
        </UButton>
      </UForm>
    </UCard>
  </div>
</template>

// front/components/SignupForm.tsx
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { signupSchema, type SignupSchema } from "@/schemas/auth.schema";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AuthResponse } from "@/types/auth.js";
import { useState } from "react";

export function SignupForm() {
  const API_URL = process.env.NEXT_PUBLIC_API_URL;
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const form = useForm<SignupSchema>({
    resolver: zodResolver(signupSchema),
    defaultValues: {
      firstname: "",
      lastname: "",
      email: "",
      password: "",
      licence: false,
      licenseNumber: "",
    },
  });

  async function onSubmit(data: SignupSchema) {
    setIsLoading(true);
    const response = await fetch(`${API_URL}/auth/signup`, {
      method: "POST",
      credentials: "include",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });

    const responseData: AuthResponse = await response.json();

    if (responseData.status === "success") {
      toast.success("Inscription réussie");
      router.push("/login");
    } else {
      toast.error("Erreur lors de l'inscription");
    }
    setIsLoading(false);
  }

  return (
    <Card className="max-w-md mx-auto">
      <CardHeader>
        <CardTitle>Inscription</CardTitle>
        <CardDescription>
          Vous avez déjà un compte ?{" "}
          <Link href="/login" className="text-blue-500">
            Connectez-vous
          </Link>
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="w-full space-y-6"
          >
            <FormField
              control={form.control}
              name="firstname"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Prénom</FormLabel>
                  <FormControl>
                    <Input className="w-full" placeholder="Jean" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="lastname"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Nom de famille</FormLabel>
                  <FormControl>
                    <Input placeholder="Dupont" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Email</FormLabel>
                  <FormControl>
                    <Input
                      type="email"
                      placeholder="jean.dupont@example.com"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="password"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Mot de passe</FormLabel>
                  <FormControl>
                    <Input type="password" placeholder="••••••••" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="licence"
              render={({ field }) => (
                <FormItem>
                  <div className="flex items-center space-x-2">
                    <Checkbox
                      id="licence"
                      checked={field.value}
                      onCheckedChange={field.onChange}
                    />
                    <FormLabel htmlFor="licence">
                      Je possède ma licence {new Date().getFullYear()}
                    </FormLabel>
                  </div>
                  <FormMessage />
                </FormItem>
              )}
            />
            {form.watch("licence") && (
              <FormField
                control={form.control}
                name="licenseNumber"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Numéro de licence</FormLabel>
                    <FormControl>
                      <Input placeholder="1234567890" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}
            <Button type="submit" disabled={isLoading}>
              {isLoading ? "En cours..." : "S'inscrire"}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
